#!/bin/bash
# Edge-pruning sweep for the mixed IOI dataset.
# Runs pruning at various edge sparsity targets to find elbow points
# for threshold calibration.
#
# Dataset: data/datasets/ioi_mixed/ (generated by prepare_ioi_mixed.py)
# Output:  data/runs/ioi_mixed-es{SPARSITY}-ns0.72/
#
# Run log: data/scripts/logs/ioi_mixed_sweep.log (via tee)
set -e

# Sparsity sweep - covering a wide range to find elbow points
EDGE_SPARSITIES=(0.90 0.92 0.94 0.96 0.97 0.975 0.98 0.985 0.99 0.995 1.0 1.02 1.05)

for i in "${!EDGE_SPARSITIES[@]}"; do

EDGE_SPARSITY=${EDGE_SPARSITIES[i]}
NODE_SPARSITY=0.72
ELR=0.8
LLR=0.8
RELR=0.8
RLLR=0.8
TOTAL=3000
WARMUP=2500

EXTRA="--disable_node_loss"
TAG="ioi_mixed"

train_split="train"
N_TRAIN=1000000
N_VAL=200

echo "============================================"
echo "Running Edge-Pruning: edge_sparsity=$EDGE_SPARSITY"
echo "============================================"

WANDB_MODE=disabled python src/prune/fpt2_ioi.py \
    --report_to wandb \
    --do_train \
    --do_eval \
    --dataset_path ./data/datasets/ioi_mixed/ \
    --train_split $train_split \
    --initialize_from gpt2 \
    --max_seq_length 64 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --eval_accumulation_steps 16 \
    --edge_learning_rate $ELR \
    --layer_learning_rate $LLR \
    --reg_edge_learning_rate $RELR \
    --reg_layer_learning_rate $RLLR \
    --max_steps $TOTAL \
    --warmup_steps 200 \
    --eval_strategy steps \
    --eval_steps 64 \
    --save_steps 64 \
    --logging_steps 8 \
    --save_total_limit 1 \
    --start_edge_sparsity 0.00 \
    --target_edge_sparsity $EDGE_SPARSITY \
    --start_layer_sparsity 0.00 \
    --target_layer_sparsity $NODE_SPARSITY \
    --num_sparsity_warmup_steps $WARMUP \
    --max_train_samples $N_TRAIN \
    --max_eval_samples $N_VAL \
    --output_dir ./data/runs/ioi-${TAG}-es${EDGE_SPARSITY}-ns${NODE_SPARSITY}/ \
    --remove_unused_columns false \
    --dataloader_num_workers 0 \
    --warmup_type linear \
    --with_embedding_nodes \
    --overwrite_output_dir \
    $EXTRA

echo "Finished edge_sparsity=$EDGE_SPARSITY"
echo ""

done

echo "============================================"
echo "All edge-pruning runs complete."
echo "Results in: data/runs/ioi_mixed-es*-ns0.72/"
echo "============================================"
